version: '3.9'

services:
  api:
    image: tilt-avatar-api
    build:
      context: tilt-avatars
      dockerfile: deploy/api.dockerfile
    expose:
      - "5000"
    labels:
      kompose.service.expose: "avatar.localdev.me/api"
      kompose.image-pull-policy: "Never"

  web:
    image: tilt-avatar-web
    command: ["yarn", "dev", "--host", "0.0.0.0"]
    build:
      context: tilt-avatars
      dockerfile: deploy/web.dockerfile
    environment:
      VITE_CLIENT_PORT: "80"
      VITE_HOST: "0.0.0.0"
    expose:
      - "5173"
    labels:
      kompose.service.expose: "avatar.localdev.me"
      kompose.image-pull-policy: "Never"

# vim: set et ts=2 sw=2:
